
		align	4
		label	L834_len__hla_ word
		dd	08h
		dd	08h
		label	L834_str__hla_ byte
		db	"largest("
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L845_len__hla_ word
		dd	01h
		dd	01h
		label	L845_str__hla_ byte
		db	","
		db	0

		db	0
		db	0

		align	4
		label	L878_len__hla_ word
		dd	09h
		dd	09h
		label	L878_str__hla_ byte
		db	") equals "
		db	0

		db	0
		db	0

		align	4
		label	L889_len__hla_ word
		dd	01h
		dd	01h
		label	L889_str__hla_ byte
		db	"!"
		db	0

		db	0
		db	0
