
		align	4
		label	L832_len__hla_ word
		dd	0ch
		dd	0ch
		label	L832_str__hla_ byte
		db	"Feed me W : "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L854_len__hla_ word
		dd	0ch
		dd	0ch
		label	L854_str__hla_ byte
		db	"Feed me X : "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L876_len__hla_ word
		dd	0ch
		dd	0ch
		label	L876_str__hla_ byte
		db	"Feed me Y : "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L898_len__hla_ word
		dd	0ch
		dd	0ch
		label	L898_str__hla_ byte
		db	"Feed me Z : "
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L922_len__hla_ word
		dd	013h
		dd	013h
		label	L922_str__hla_ byte
		db	"Not the same. AL = "
		db	0


		align	4
		label	L947_len__hla_ word
		dd	0bh
		dd	0bh
		label	L947_str__hla_ byte
		db	"Same. AL = "
		db	0

