		label	L815_fpconst__hla_ tword
		dt	 4.00000000000000000e+0000
		label	L816_fpconst__hla_ tword
		dt	 6.00000000000000000e+0000
		label	L817_fpconst__hla_ tword
		dt	 2.00000000000000000e+0000

		align	4
		label	L831_len__hla_ word
		dd	02eh
		dd	02eh
		label	L831_str__hla_ byte
		db	"Lemme calculate the volumes of various things!"
		db	0

		db	0

		align	4
		label	L849_len__hla_ word
		dd	0ah
		dd	0ah
		label	L849_str__hla_ byte
		db	"Gimme r : "
		db	0

		db	0

		align	4
		label	L871_len__hla_ word
		dd	0ah
		dd	0ah
		label	L871_str__hla_ byte
		db	"Gimme h : "
		db	0

		db	0

		align	4
		label	L893_len__hla_ word
		dd	01bh
		dd	01bh
		label	L893_str__hla_ byte
		db	"Surface Area of a sphere = "
		db	0


		align	4
		label	L907_len__hla_ word
		dd	0eh
		dd	0eh
		label	L907_str__hla_ byte
		db	" square inches"
		db	0

		db	0

		align	4
		label	L925_len__hla_ word
		dd	019h
		dd	019h
		label	L925_str__hla_ byte
		db	"Surface Area of a cube = "
		db	0

		db	0
		db	0

		align	4
		label	L957_len__hla_ word
		dd	01dh
		dd	01dh
		label	L957_str__hla_ byte
		db	"Surface Area of a cylinder = "
		db	0

		db	0
		db	0
