
		align	4
		label	L821_len__hla_ word
		dd	019h
		dd	019h
		label	L821_str__hla_ byte
		db	"Gimme a starting value : "
		db	0

		db	0
		db	0

		align	4
		label	L858_len__hla_ word
		dd	0ah
		dd	0ah
		label	L858_str__hla_ byte
		db	"Quad Table"
		db	0

		db	0

		align	4
		label	L876_len__hla_ word
		dd	03h
		dd	03h
		label	L876_str__hla_ byte
		db	" : "
		db	0


		align	4
		label	L890_len__hla_ word
		dd	01h
		dd	01h
		label	L890_str__hla_ byte
		db	" "
		db	0

		db	0
		db	0
