		label	L810_fpconst__hla_ tword
		dt	 8.99900000000000000e+0001

		align	4
		label	L826_len__hla_ word
		dd	012h
		dd	012h
		label	L826_str__hla_ byte
		db	"that's the grade: "
		db	0

		db	0
		label	L841_fpconst__hla_ tword
		dt	 7.99900000000000000e+0001
		label	L871_fpconst__hla_ tword
		dt	 6.99900000000000000e+0001
		label	L901_fpconst__hla_ tword
		dt	 5.99900000000000000e+0001

		align	4
		label	L958_len__hla_ word
		dd	0ah
		dd	0ah
		label	L958_str__hla_ byte
		db	"Feed ME : "
		db	0

		db	0
