
		align	4
		label	L825_len__hla_ word
		dd	013h
		dd	013h
		label	L825_str__hla_ byte
		db	"Provide a letter : "
		db	0


		align	4
		label	L847_len__hla_ word
		dd	08h
		dd	08h
		label	L847_str__hla_ byte
		db	"summing("
		db	0

		db	0
		db	0
		db	0

		align	4
		label	L858_len__hla_ word
		dd	09h
		dd	09h
		label	L858_str__hla_ byte
		db	") equals "
		db	0

		db	0
		db	0

		align	4
		label	L880_len__hla_ word
		dd	01h
		dd	01h
		label	L880_str__hla_ byte
		db	"!"
		db	0

		db	0
		db	0
